## Primer 2. Feature-based functions

Funkcije zasnovane na atributima (eng. *feature based functions*) direktno koriste atribute elemenata (ne koriste matricu sličnosti nastalu na osnovu tih atributa). Zbog ovog svojstva, nije im potreban dodatan memorijski prostor $O(n^2)$ za cuvanje matrice sličnosti, te su pogodnije za rad sa velikim skupovima podataka.<br />

Opšti oblik *feature-based* funkcije je: <br />
$f(X)=\displaystyle \sum_{d=1}^{D} \omega_{d} \phi (\displaystyle \sum_{x \in X}  x_{d})$ <br />

gde je $f$ funkcija, $X \subseteq Y$, Y je ceo skup podataka, $d$ je jedan atribut u tom skupu, $D$ je ukupan broj atributa, $\omega_{d}$ je težina atributa $d$, $x$ je element iz skupa $X$, a $x_{d}$ je vrednost atributa $d$ za element $x$, a $\phi$ je konveksna funkcija (na primer *sqrt* ili *log*). Funkcija $\phi$ obezbeđuje svojstvo iščezavanja (eng. *diminishing returns property*). <br />
Bitno je naglasiti da za izračunavanje funkcije $f$ nije potreban ceo skup, već samo njegov podskup $X$, što utiče na brzinu njenog izračunavanja.

Maksimizacijom funkcije zasnovane na atributima izdvaja se podskup elemenata čije su vrednosti atributa velike. Zbog toga se koriste kada svaki atribut predstavlja neki kvalitet/osobinu elementa (gde veća vrednost znaci veću zastupljenost te osobine, a $0$ znači da element nema tu osobinu). Vrednosti atributa ne mogu biti negativne.

Napomena: Korišćenje funkcija zasnovane na atributima nije uvek najbolje rešenje. Pretpostavka da svaki atribut predstavlja neki smisleni kvalitet elementa ima smisla u nekim slučajevima, ali na primer, nema smisla ukoliko je element slika, gde su njeni atrbuti vrednosti piksela.
Moguće je transformisati ulazni skup podataka i tek onda koristiti ove funkcije.

In [1]:
from apricot import FeatureBasedSelection
from sklearn.datasets import load_iris
import numpy as np
from matplotlib import pyplot as plt

https://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html <br />
"This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray"

In [2]:
X, y = load_iris(return_X_y=True)

In [3]:
print('X.shape:', X.shape)
print('y.shape:', y.shape)

X.shape: (150, 4)
y.shape: (150,)


In [4]:
print('Jedinstvene vrednosti y:', np.unique(y))

Jedinstvene vrednosti y: [0 1 2]


In [5]:
n_samples = 10

In [6]:
selection_sqrt = FeatureBasedSelection(n_samples, 'sqrt', optimizer='two-stage')
X_subset_sqrt = selection_sqrt.fit_transform(X)

In [7]:
print('X_subset_sqrt.shape:', X_subset_sqrt.shape)

X_subset_sqrt.shape: (10, 4)


In [8]:
X_subset_sqrt.mean()

4.7875

In [9]:
X.mean()

3.4644999999999997

U nastavku koristim drugu funkciju sličnosti (log) a zatim poredim rezultat sa prethodnim. 

In [10]:
selection_log = FeatureBasedSelection(n_samples, 'log', optimizer='two-stage')
X_subset_log = selection_log.fit_transform(X)

In [11]:
# kreiram skupove za izabrane elemente kako bih ih poredila posle.
X_subset_log_set = set()
for i in X_subset_log:
    X_subset_log_set.add(tuple(i))
    
X_subset_sqrt_set = set()
for i in X_subset_sqrt:
    X_subset_sqrt_set.add(tuple(i))

In [12]:
if np.alltrue(X_subset_log_set == X_subset_sqrt_set):
    print('Izabrani podskupovi koristeći funkcije sqrt i log su isti i iznose:\n', X_subset_sqrt)
else:
    print('Izabrani podskupovi koristeći funkcije sqrt i log se razlikuju.') 
    print('Podskup dobijen koriscenjem funkcije sqrt je:\n', X_subset_log)
    print('Podskup dobijen koriscenjem funkcije log je:\n', X_subset_sqrt)

Izabrani podskupovi koristeći funkcije sqrt i log su isti i iznose:
 [[7.7 3.8 6.7 2.2]
 [7.9 3.8 6.4 2. ]
 [7.2 3.6 6.1 2.5]
 [7.7 2.6 6.9 2.3]
 [7.6 3.  6.6 2.1]
 [7.7 3.  6.1 2.3]
 [7.7 2.8 6.7 2. ]
 [6.7 3.3 5.7 2.5]
 [6.3 3.3 6.  2.5]
 [6.8 3.2 5.9 2.3]]


U nastavku koristim trecu funkciju sličnosti (sigmoidnu funkciju):

In [13]:
selection_sigmoid = FeatureBasedSelection(n_samples, 'sigmoid', optimizer='two-stage')
X_subset_sigmoid = selection_sigmoid.fit_transform(X)

In [14]:
X_subset_sigmoid_set = set()
for i in X_subset_sigmoid:
    X_subset_sigmoid_set.add(tuple(i))

In [15]:
if np.alltrue(X_subset_sigmoid_set == X_subset_sqrt_set):
    print('Izabrani podskupovi koristeći funkcije sqrt i log su isti.')
else:
    print('Izabrani podskupovi koristeći funkcije sqrt i sigmoid se razlikuju.')
    print('Podskup dobijen koriscenjem funkcije sigmoid je:\n', X_subset_sigmoid)

Izabrani podskupovi koristeći funkcije sqrt i sigmoid se razlikuju.
Podskup dobijen koriscenjem funkcije sigmoid je:
 [[7.7 3.8 6.7 2.2]
 [7.2 3.6 6.1 2.5]
 [6.7 3.3 5.7 2.5]
 [6.3 3.3 6.  2.5]
 [7.9 3.8 6.4 2. ]
 [6.3 3.4 5.6 2.4]
 [7.7 3.  6.1 2.3]
 [6.8 3.2 5.9 2.3]
 [6.7 3.1 5.6 2.4]
 [6.9 3.2 5.7 2.3]]
