## Primer 4. Sample weight

Ovaj primer demonstrira korišćenje informacije o težini elemenata. Prilikom optimizacije se koriste prosleđene težine (odnosno cena) elemenata umesto uobičajenog ograničenja za kardinalnost elemenata.  <br />
Na početku je dat opšti primer korišćenja težina, a zatim je rešen i problem ranca.

In [1]:
from apricot import FeatureBasedSelection
import numpy
from sklearn import preprocessing

Primer 4.a: Slučajno generisan niz podataka i težinama.

In [2]:
X = numpy.random.randint(2, size=(10000, 100))
sample_cost = numpy.abs(numpy.random.randn(10000))

selector = FeatureBasedSelection(100, 'sqrt')
selector.fit(X, sample_cost=sample_cost)

In [3]:
X_transformed = selector.transform(X)
X_transformed.shape

(1245, 100)

Primer 4.b: Problem ranca (primer sa vežbi)

In [4]:
items = ['hat', 'sunglasses', 'book', 'towel', 'snorkeling kit', 'food']
values = {'hat':2, 'sunglasses':8, 'book':3, 'towel':4, 'snorkeling kit': 100, 'food': 1}
costs = {'hat':0.1, 'sunglasses':0.1, 'book':0.2, 'towel':0.3, 'snorkeling kit': 0.6, 'food': 10}
max_cost = 0.9
n = len(items)

In [5]:
#X = numpy.array([1]*len(items)).reshape(n, 1)
X = numpy.array([ values[item] for item in items]).reshape(n, 1)
labels = numpy.array(items).reshape(n, 1)
knapsack_costs = numpy.array([costs[item] for item in items])#.reshape(n, 1)

In [6]:
knapsack_costs

array([ 0.1,  0.1,  0.2,  0.3,  0.6, 10. ])

In [7]:
selector_knapsack = FeatureBasedSelection(max_cost, 'sqrt')

# NOTE: Prema zvanicnoj dokumentaciji, sample_weight parameter je za sada ignorisan. 
# ("but included to maintain compatibility with sklearn pipelines")
result = selector_knapsack.fit_transform(X, y=labels, sample_weight=knapsack_costs, sample_cost=knapsack_costs)

X_subset = result[0]
Y_subset = result[1]

In [8]:
result

(array([[  8],
        [100],
        [  2]]),
 array([['sunglasses'],
        ['snorkeling kit'],
        ['hat']], dtype='<U14'),
 array([0.1, 0.6, 0.1]))

In [9]:
print('Izabrani elementi : cena: ')
for item in Y_subset:
    print('\t{0} : {1}'.format(item[0], costs[item[0]]))
print('Ukupna cena: ', result[2].sum())
print('Ukupna vrednost: ', X_subset.sum())

Izabrani elementi : cena: 
	sunglasses : 0.1
	snorkeling kit : 0.6
	hat : 0.1
Ukupna cena:  0.7999999999999999
Ukupna vrednost:  110
